services:
  peque_bot:
    build: .
    container_name: ${CONTAINER_NAME}
    env_file:
      - .env
    volumes:
      - ${VIDEOS_DIR}:/app/videos
      - ./logs:/app/logs
    restart: unless-stopped